### ISSUE TITLE
How to modify Text inside listItem?

### ISSUE THREAD

**Issue by franciscorosso** [dasautoooo/Parma#20]
Hi @dasautoooo! Parma is working really fine on what I was doing, but there is just one thing I can't achieve yet:

Is there a way to modify the Text view inside the `listItem` method without using the `plainText` one?

In my case I have both a heading and a bullet list, so If I modify the Text view inside the `plainText` method the Text view inside `heading` is also being modified, and I don't want that. I already tried with `paragraph` but nothing happens.

Thanks in advance,
Francisco.

**Comment by dasautoooo** [comment]
Hi @franciscorosso ,

You can just apply `.font()` modifier to the view which the function `listItem(attributes:index:view:)` provides.

It is not recommended to modify `plainText` in `ParmaRenderable` anyway.

Thank you for your feedback 😊.

**Comment by franciscorosso** [comment]
> Hi @franciscorosso ,
> 
> You can just apply `.font()` modifier to the view which the function `listItem(attributes:index:view:)` provides.
> 
> It is not recommended to modify `plainText` in `ParmaRenderable` anyway.
> 
> Thank you for your feedback 😊.

Thanks @dasautoooo for your fast response! It worked perfect!
