### ISSUE TITLE
Custom Tags

### ISSUE THREAD

**Issue by mamilov** [dasautoooo/Parma#23]
Hi, is it possible to add custom tags and define their appearance?
For example:
```
[Detail](This is a detail text)
```

**Comment by dasautoooo** [comment]
Hi @mamilov ,
I don't know what is this syntax in common markdown? 
Do you mean to add new custom syntax?

**Comment by mamilov** [comment]
Hi @dasautoooo,
Yes, I'd like to add custom syntax in order render custom views.
