### ISSUE TITLE
Parma won't compile on macOS 10.15

### ISSUE THREAD

**Issue by dominikmayer** [dasautoooo/Parma#6]
Both the latest release and the main branch (pictured below) fail to compile on my macOS 10.15.7:

<img width="979" alt="Bildschirmfoto 2020-10-24 um 01 08 45" src="https://user-images.githubusercontent.com/159476/97038753-7dcf9a80-1595-11eb-852d-250bacf1c59d.png">

**Comment by dasautoooo** [comment]
Hi Dominik,

Thank you for your feedback. This problem has already been fixed in the latest release (v0.2.0).

**Comment by dominikmayer** [comment]
Great. Thank you!
